#!/bin/bash

entries="⇠ \u00a0 Logout \n ⏾ \u00a0 Suspend \n ⭮ \u00a0  Reboot \n ⏻  \u00a0 Shutdown"

selected=$(echo -e $entries|wofi --width 200 --height 200 --dmenu --cache-file /dev/null | awk '{print tolower($2)}')

case $selected in
  logout)
    swaymsg exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
